language: node_js
node_js: stable
before_script:
- bower install --silent
addons:
  sauce_connect: true
script:
- npm run lint
- polymer test --plugin sauce --job-name "arc-project-selector:${TRAVIS_BRANCH}" --build-number=${TRAVIS_BUILD_NUMBER}
cache:
  directories:
  - node_modules
branches:
  only:
  - stage
  - develop
after_success:
- node tasks/ci.js
env:
  global:
  - secure: 1hfjylceWBlx3lzcJ/B8RuyzcDHrSzFq92nGVYmdqrdT4paOfLrx7mZp808fizSuM+80ckf9emuHeyXs+5UvKeuVUC0Tj2ZskdBJlbe8DcxRWNTKaAfPYvCtFcgPXhUSaK2/6Qgpv61J5nGuYX68DPbk9LEf7zbHNK7/DWq6BF/Tdex2ty0EZeuFlugyuiWi/Yj41qREBC6es31pB+Ryo3qIb6TkkZMbtB4UIOEHSi6o/yv5D8m5Bu74H44R0AtGvZe8cUwBOhlqvG+cMKx7rUfujSHzFMclJiBAps462XXthYgVUzLUZeSEaMrrjo9oRjSUYA7j6/ytJroj7OEip8X0vc7tSoAvPUUEwTiAZO+G931YLPf630usvcbrUvHUfjv16+vjTTladir2CnHQSkMgs7TW417X7jR0VfOyNdUoAh78OeN+9LMPGFB4mmYDaIuF5Hzn4XJLg5M6CxIwY7l/dHL9FwG61ksR4S0O1KZajHoGtFL0gr1NtR4VvIISH3ooxLbNO3nAK+9q7jT4t0IZtR5QAtjSu0X/9hreRDOl7/iq/XOmD027N74VnIy7DOSqiRupq7qZ46gsc0hf3MtWrER4moqdEn+zKV4iMtLuQWktY/QhFd6AW1yVYPUKn7AmkH0PUj2gKSqCBP0DY7CYcndRr9PhEw8+XJw8STc=
  - secure: ZybX9jCplNZ5/Wu5UbOuOG2qxTBxyBy/kX+iqbURaei7WyUjRqH9gIXRRZZ2FwQZ7MRxLfNZlGer5EpCqfOMqpj4PG0S3v1RT3vuP3aX/fOdC2HMmXiyhuE6dxld88iopEFeDp3CMWV9fL3mXZ8/raHDSdMl8yHJsz+2hubhw+GmY7xl/qMTJ68eRzsQJBSU8u/H0LAd2MXN4CLp2U3i7RB16ASscRzJxXtwBy1DgWSKWS0z8MR2PPi/Jdzp1ewYEnfSB2Yr6sKoy+FKlXxQ1YNRwfcE+hqlMrklkbWpDvR2sw7B3Qagbp252qI3f2A3VnsrwuDixbXSMDqz8Bxqyo2C+nLFylPkB//y5aWdH+aYrKbnXwhVFVcbuKiseIr3WRR9m5EdIsDR9M6WulIscrxP7EaC03KH6oEUK1Si0mDkrA/vfLrTcwM7+EMgc3Xzzym9732wKWByZ04E4wW2QnAxC6nD6Z7nTIpqHUDwt/572iKThC6JM3jliw7yiOlnYnzeGY+O5HNtDGqgwJQkVhfgAwNGTNQ+0wUA3STmwy4VrzYHgCL+lkauhAMfKsdybMqc1H214YqHA8vPRwYsjQzkM/sFhoPYaEHmP2SU34p+o1/d+L1ZPNFeAy6xFEeuYvXM+PR33DvKoJn1xWH85sqrydIN/LlI2ac1/yjN1lY=
